/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyTiredRouteImport } from './routes/why-tired'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicKlaviyoSubscribeRouteImport } from './routes/api/public/klaviyo-subscribe'

const WhyTiredRoute = WhyTiredRouteImport.update({
  id: '/why-tired',
  path: '/why-tired',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKlaviyoSubscribeRoute =
  ApiPublicKlaviyoSubscribeRouteImport.update({
    id: '/api/public/klaviyo-subscribe',
    path: '/api/public/klaviyo-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/why-tired': typeof WhyTiredRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/klaviyo-subscribe': typeof ApiPublicKlaviyoSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/why-tired': typeof WhyTiredRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/klaviyo-subscribe': typeof ApiPublicKlaviyoSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/why-tired': typeof WhyTiredRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/klaviyo-subscribe': typeof ApiPublicKlaviyoSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/why-tired'
    | '/product/$slug'
    | '/api/public/klaviyo-subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/why-tired'
    | '/product/$slug'
    | '/api/public/klaviyo-subscribe'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/why-tired'
    | '/product/$slug'
    | '/api/public/klaviyo-subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  WhyTiredRoute: typeof WhyTiredRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicKlaviyoSubscribeRoute: typeof ApiPublicKlaviyoSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-tired': {
      id: '/why-tired'
      path: '/why-tired'
      fullPath: '/why-tired'
      preLoaderRoute: typeof WhyTiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/klaviyo-subscribe': {
      id: '/api/public/klaviyo-subscribe'
      path: '/api/public/klaviyo-subscribe'
      fullPath: '/api/public/klaviyo-subscribe'
      preLoaderRoute: typeof ApiPublicKlaviyoSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  WhyTiredRoute: WhyTiredRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicKlaviyoSubscribeRoute: ApiPublicKlaviyoSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
