/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StripsRouteImport } from './routes/strips'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlowRouteImport } from './routes/glow'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicKlaviyoSubscribeRouteImport } from './routes/api/public/klaviyo-subscribe'

const StripsRoute = StripsRouteImport.update({
  id: '/strips',
  path: '/strips',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlowRoute = GlowRouteImport.update({
  id: '/glow',
  path: '/glow',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKlaviyoSubscribeRoute =
  ApiPublicKlaviyoSubscribeRouteImport.update({
    id: '/api/public/klaviyo-subscribe',
    path: '/api/public/klaviyo-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/glow': typeof GlowRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/strips': typeof StripsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/klaviyo-subscribe': typeof ApiPublicKlaviyoSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/glow': typeof GlowRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/strips': typeof StripsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/klaviyo-subscribe': typeof ApiPublicKlaviyoSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/glow': typeof GlowRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/strips': typeof StripsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/klaviyo-subscribe': typeof ApiPublicKlaviyoSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/glow'
    | '/login'
    | '/privacy'
    | '/shop'
    | '/strips'
    | '/admin/analytics'
    | '/product/$slug'
    | '/api/public/klaviyo-subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/glow'
    | '/login'
    | '/privacy'
    | '/shop'
    | '/strips'
    | '/admin/analytics'
    | '/product/$slug'
    | '/api/public/klaviyo-subscribe'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/contact'
    | '/glow'
    | '/login'
    | '/privacy'
    | '/shop'
    | '/strips'
    | '/admin/analytics'
    | '/product/$slug'
    | '/api/public/klaviyo-subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  GlowRoute: typeof GlowRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  StripsRoute: typeof StripsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicKlaviyoSubscribeRoute: typeof ApiPublicKlaviyoSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strips': {
      id: '/strips'
      path: '/strips'
      fullPath: '/strips'
      preLoaderRoute: typeof StripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glow': {
      id: '/glow'
      path: '/glow'
      fullPath: '/glow'
      preLoaderRoute: typeof GlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/klaviyo-subscribe': {
      id: '/api/public/klaviyo-subscribe'
      path: '/api/public/klaviyo-subscribe'
      fullPath: '/api/public/klaviyo-subscribe'
      preLoaderRoute: typeof ApiPublicKlaviyoSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  GlowRoute: GlowRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  StripsRoute: StripsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicKlaviyoSubscribeRoute: ApiPublicKlaviyoSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
